# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: true
cache: packages
sudo: required
dist: trusty

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev
  - sudo apt-get install r-cran-ncdf4
  
addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ubuntugis-unstable'
    packages:
      - libudunits2-dev
      - libnetcdf-dev
      - libproj-dev
      - libgeos-dev
      - libgdal-dev
      - netcdf-bin

script: 
  - R -f tests/render_rmds.R
